from importlib.metadata import version

from . import types
from .browser import (
    Browser,
    BrowserPool,
    CapturedResponse,
    CDPClient,
    CDPError,
    Page,
    PoolHandler,
    PoolOptions,
    PoolOutcome,
    StopRun,
)
from .client import AsyncSurfsky, Surfsky
from .errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    BrowserTimeoutError,
    ConfigurationError,
    ConflictError,
    ForbiddenError,
    MonthlySessionLimitError,
    NotFoundError,
    PageClosedError,
    PaymentRequiredError,
    PremiumTrafficLimitError,
    RateLimitError,
    ServerError,
    SharedTrafficLimitError,
    SurfskyError,
)
from .proxy import (
    ProxyCycle,
    ProxyFactory,
    ProxyInput,
    ProxyRandom,
    ProxySource,
    ProxyTemplate,
)
from .resources.profiles import ProfileUpdate, SessionOptions
from .types import *  # noqa: F403

__version__ = version("surfsky")

__all__ = [
    "__version__",
    "Surfsky",
    "AsyncSurfsky",
    "SessionOptions",
    "ProfileUpdate",
    "Browser",
    "Page",
    "BrowserPool",
    "CapturedResponse",
    "PoolHandler",
    "PoolOptions",
    "PoolOutcome",
    "StopRun",
    "CDPClient",
    "CDPError",
    "BrowserTimeoutError",
    "PageClosedError",
    "ProxySource",
    "ProxyCycle",
    "ProxyRandom",
    "ProxyTemplate",
    "ProxyFactory",
    "ProxyInput",
    "SurfskyError",
    "ConfigurationError",
    "APIError",
    "APIConnectionError",
    "APITimeoutError",
    "BadRequestError",
    "AuthenticationError",
    "PaymentRequiredError",
    "ForbiddenError",
    "NotFoundError",
    "ConflictError",
    "RateLimitError",
    "SharedTrafficLimitError",
    "PremiumTrafficLimitError",
    "MonthlySessionLimitError",
    "ServerError",
    *types.__all__,
]
